#!/bin/bash

echo "Running Install"

echo "./console phpci:install\
 --url=$PHPCI_URL\
 --db-host=$PHPCI_DB_HOST\
 --db-name=$PHPCI_DB_NAME\
 --db-user=$PHPCI_DB_USER\
 --db-pass=$PHPCI_DB_PASSWORD\
 --admin-name=$PHPCI_ADMIN_LOGIN\
 --admin-pass=$PHPCI_ADMIN_PASSWORD\
 --admin-mail=$PHPCI_ADMIN_MAIL"

./console phpci:install\
 --url=$PHPCI_URL\
 --db-host=$PHPCI_DB_HOST\
 --db-name=$PHPCI_DB_NAME\
 --db-user=$PHPCI_DB_USER\
 --db-pass=$PHPCI_DB_PASSWORD\
 --admin-name=$PHPCI_ADMIN_LOGIN\
 --admin-pass=$PHPCI_ADMIN_PASSWORD\
 --admin-mail=$PHPCI_ADMIN_MAIL

echo "Activating htaccess and Fixing permissions"

mv public/.htaccess.dist public/.htaccess
chown -R www-data:root .

php daemonise phpci:daemonise &

apache2-foreground