#!/bin/bash

echo "Running data"

./console phpci:install\
 --url=$PHPCI_URL\
 --db-host=$PHPCI_DB_HOST\
 --db-name=$PHPCI_DB_NAME\
 --db-user=$PHPCI_DB_USER\
 --db-pass=$PHPCI_DB_PASSWORD\
 --admin-name=$PHPCI_ADMIN_LOGIN\
 --admin-pass=$PHPCI_ADMIN_PASSWORD\
 --admin-mail=$PHPCI_ADMIN_MAIL

mv public/.htaccess.dist public/.htaccess
php daemonise phpci:daemonise &

apache2-foreground